### ISSUE TITLE
regex not sufficient

### ISSUE THREAD

**Issue by DanielRuf** [mirkoschubert/minimal-contact-form#1]
`/^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/`

This does not cover many cases (umlauts, long gTLDs, i18n).
In general the PHP (FILTER_VALIDATE_EMAIL) and client side validation (type=email) features should be used.

Always try to prevent the usage of regular expressions. This should be the very last solution for problems which can be solved in a more suncatic sugar way with native methods.

Also regex is abit eval as it consumes more memory than alternative methods as they are compiled in the memory which results in longer commands on the callstack.

**Comment by mirkoschubert** [comment]
Sorry, I was in SVN hell until now... 😆 
I will work on the regex on Monday. You're right, there are a lot of use cases missing (but umlauts are the least interesting ones, since there are very few email services who support them anyway).

Regards your point of view about regular expressions I have to respectfully disagree. I won't renounce JavaScript validation. Certainly I could validate with php since I'm sending it via AJAX anyways, but the way back is the problem. I'm even not happy about the error message, which I send back and forth only to have them translated. It costs me about half a second to show the translated string and it would be the same with the validation. That's much longer than one regex. 😄 If you have a better idea I'm open for it.

HTML5 validation won't work with JavaScript since I can't use a submit button. And I doubt that I could design them like I want instead of having those ugly bubbles.

**Comment by DanielRuf** [comment]
You do not need a submit button. Browsers have the forms validation API and support type=email.

FILTER_VALIDATE_EMAIL is generally faster than regex.
Also the official regex for emails is much longer, see http://emailregex.com/

regex is slow / slower

**Comment by DanielRuf** [comment]
Not sure why the way back should be a problem and in which way as you can always use json_encode.

**Comment by DanielRuf** [comment]
Also see https://www.npmjs.com/package/isemail

**Comment by DanielRuf** [comment]
https://stackoverflow.com/a/1076589/753676

> "How do I validate an email with regex" is one of the more popular questions that come up when it comes to regular expressions and the only real good answer is "you don't".

https://stackoverflow.com/a/508121/753676

**Comment by mirkoschubert** [comment]
Haha, `isemail`uses regex, every jQuery plugin uses regex, even the type=email uses regex (as stated at emailregex.com) - I bet php does the same internally. 😄 
But thank you for the tips, I look over it!

Try my testing site: http://wpdev.mirkoschubert.de/contact/ 😏 Just press `Submit` without anything in it - you see what I mean. And I tested it - it is the JavaScript (JQuery ajax), not the translation process.

**Comment by mirkoschubert** [comment]
Oh, and I use type=email ;) But since I switched out the submit button with a normal one, there's no HTML5 validation anymore.

**Comment by DanielRuf** [comment]
There is always HTML5 validation.
You can still use `checkValidity` and `:valid` / `:invalid`

See https://codepen.io/DanielRuf/pen/QxxrMW

**Comment by DanielRuf** [comment]
> I bet php does the same internally.

Sure but these are faster and better.
Why reinvent the wheel when there is already everything that you need and also faster and more reliable? ;-)

**Comment by DanielRuf** [comment]
Regarding forms without a submit button: this is bad for a11y and UX. And there is always event.preventDefault() and so on =)
